[package]
name = "gameboy"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[dependencies]
pixels = "0.15.0"
winit = "0.29.15"
blip_buf = "0.1.5"
rodio = "0.20.1"